
/* Copyright 2015-present Samsung Electronics Co., Ltd. and other contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is generated by tools/js2c.py
 * Do not modify this.
 */
#ifndef _JS_SNAPSHOTS_H_
#define _JS_SNAPSHOTS_H_

extern const char app_n[];
extern const uint8_t app_s[];
extern const size_t app_l;

extern const char assert_n[];
extern const uint8_t assert_s[];
extern const size_t assert_l;

extern const char config_n[];
extern const uint8_t config_s[];
extern const size_t config_l;

extern const char console_n[];
extern const uint8_t console_s[];
extern const size_t console_l;

extern const char events_n[];
extern const uint8_t events_s[];
extern const size_t events_l;

extern const char flora_cli_n[];
extern const uint8_t flora_cli_s[];
extern const size_t flora_cli_l;

extern const char global_n[];
extern const uint8_t global_s[];
extern const size_t global_l;

extern const char httpsession_n[];
extern const uint8_t httpsession_s[];
extern const size_t httpsession_l;

extern const char process_n[];
extern const uint8_t process_s[];
extern const size_t process_l;

extern const char speech_monitor_n[];
extern const uint8_t speech_monitor_s[];
extern const size_t speech_monitor_l;

extern const char timers_n[];
extern const uint8_t timers_s[];
extern const size_t timers_l;

extern const char util_n[];
extern const uint8_t util_s[];
extern const size_t util_l;

extern const char wifi_monitor_n[];
extern const uint8_t wifi_monitor_s[];
extern const size_t wifi_monitor_l;

typedef struct {
  const char* name;
  const void* code;
  const size_t length;
} js_snapshot_module_t;

extern const js_snapshot_module_t js_modules[];
extern const size_t js_modules_size;

#endif // _JS_SNAPSHOTS_H_
